# Generated by Django 4.2.6 on 2023-10-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="products/thumbnails/"),
        ),
    ]
